# Generated by Django 2.2.3 on 2019-07-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190718_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(upload_to='media/blog/images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_on',
            field=models.DateField(editable=False),
        ),
    ]
