# Generated by Django 2.2.3 on 2019-07-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190721_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_on',
            field=models.DateField(null=True),
        ),
    ]
